### ISSUE TITLE
applyMiddleware type does not allow heterogeneously-typed middleware

### ISSUE THREAD

**Issue by jfirebaugh** [reduxjs/redux#3426]
**Do you want to request a _feature_ or report a _bug_?**

Report a bug.

**What is the current behavior?**

Consider the following TypeScript program, minimized from a production use case:

```ts
import {Middleware, Reducer, applyMiddleware, createStore} from "redux";

type A = { a: string }
type B = { b: string }

const middlewareA: Middleware<{}, A> = (store) => (next) => (action) => next(action);
const middlewareB: Middleware<{}, B> = (store) => (next) => (action) => next(action);

const reducer: Reducer<A & B> = (state) => state;

createStore(reducer, applyMiddleware(middlewareA, middlewareB));
```

In practice `middlewareA` and `middlewareB` deal with two separate domains and are defined in separate modules. They declare themselves as receiving only the state they know about.

I should be able to use both middleware simultaneously in a larger program whose aggregate state extends `A & B`, as shown. However, this produces a type error:

```
index.ts:11:51 - error TS2345: Argument of type 'Middleware<{}, B, Dispatch<AnyAction>>' is not assignable to parameter of type 'Middleware<{}, A, any>'.
  Property 'a' is missing in type 'B' but required in type 'A'.

11 createStore(reducer, applyMiddleware(middlewareA, middlewareB));
                                                     ~~~~~~~~~~~

  index.ts:3:12
    3 type A = { a: string }
                 ~
    'a' is declared here.

```

**Which versions of Redux?**
4.0.1

**Did this work in previous versions of Redux?**
Yes. The following works in 3.7.2:

```ts
import {Middleware, Reducer, applyMiddleware, createStore} from "redux";

type A = { a: string }
type B = { b: string }

const middlewareA: Middleware = (store) => (next) => (action) => next(action);
const middlewareB: Middleware = (store) => (next) => (action) => next(action);

const reducer: Reducer<A & B> = (state) => state;

createStore(reducer, applyMiddleware(middlewareA, middlewareB));
```

**Comment by timdorr** [comment]
You can just do what we do in our tests with a small implementation of Thunks and create a State type argument for your middleware: https://github.com/reduxjs/redux/blob/74233481ab3a10611861dc34106819f203f82477/test/typescript/middleware.ts#L71-L82

Because at the call site of createStore/applyMiddleware, you should know your State type, that should be passable at that point.

**Comment by jfirebaugh** [comment]
Hmm, I don't think I understand the relevancy of that code. The problem is not that I don't know the state types involved, or that they need to be made generic. It's that the type definition for `applyMiddleware` doesn't support the composition of middleware that deal with different pieces of state.

```ts
export function applyMiddleware<Ext1, Ext2, S>(
  middleware1: Middleware<Ext1, S, any>,
  middleware2: Middleware<Ext2, S, any>
): StoreEnhancer<{ dispatch: Ext1 & Ext2 }>
```

This definition requires that `middleware1` and `middleware2` both be typed as accepting the same state `S`. That's more restrictive than it should be.
